import React, { useState } from 'react';
import { Copy, Check, Database, Terminal, Shield } from 'lucide-react';

interface SqlSchemaModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const SqlSchemaModal: React.FC<SqlSchemaModalProps> = ({ isOpen, onClose }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const sqlCode = `-- 1. Create items table
create table public.items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. Prevent duplicate item names for the same user (case-insensitive)
create unique index items_user_id_name_unique
on public.items (user_id, lower(name));

-- 3. Enable Row Level Security (RLS)
alter table public.items enable row level security;

-- 4. RLS Policies
create policy "Users can view their own items"
on public.items
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own items"
on public.items
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own items"
on public.items
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own items"
on public.items
for delete
to authenticated
using (auth.uid() = user_id);`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col max-h-[90vh]">
        <div className="p-5 border-b border-slate-800 flex items-center justify-between bg-slate-950/50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
              <Database className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white">Supabase Database Setup SQL</h2>
              <p className="text-xs text-slate-400">Run this in your Supabase SQL Editor to create the required table & RLS policies</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white text-sm font-medium px-3 py-1.5 rounded-lg hover:bg-slate-800 transition"
          >
            Close
          </button>
        </div>

        <div className="p-6 overflow-y-auto space-y-4">
          <div className="bg-amber-500/10 border border-amber-500/20 rounded-xl p-4 text-amber-200/90 text-xs flex items-start gap-3">
            <Shield className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
            <div>
              <span className="font-semibold block text-amber-300 mb-0.5">Required for Item Management & RLS</span>
              Make sure you execute this SQL script in your Supabase project's SQL Editor tab so that the authenticated users can securely manage their personal items.
            </div>
          </div>

          <div className="relative group">
            <div className="absolute right-3 top-3 z-10">
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium border border-slate-700 transition shadow-sm"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
                {copied ? 'Copied SQL!' : 'Copy SQL'}
              </button>
            </div>
            <pre className="bg-slate-950 border border-slate-800 rounded-xl p-4 text-slate-300 font-mono text-xs overflow-x-auto leading-relaxed max-h-80">
              {sqlCode}
            </pre>
          </div>
        </div>

        <div className="p-4 border-t border-slate-800 bg-slate-950/50 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 bg-indigo-600 hover:bg-indigo-500 text-white font-medium text-sm rounded-xl transition shadow-lg shadow-indigo-600/20"
          >
            Got it, thanks
          </button>
        </div>
      </div>
    </div>
  );
};
